extends: default

yaml-files:
  - 'yamllint.conf'
  - '*.yml'
  - '*.yaml'

ignore: |
  .terraform/
  .eirctl/
  local/
  outputs/
  tmp/

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length: disable
  truthy: disable
