# yaml-language-server: $schema=https://raw.githubusercontent.com/Ensono/eirctl/refs/heads/main/schemas/schema_v1.json

# Import remote contexts and tasks for eirctl
import:
  - git::ssh://git@github.com/thepaulmacca-ensono/eirctl-shared-scripts.git//shared/contexts/eirctl.yaml
  - git::ssh://git@github.com/thepaulmacca-ensono/eirctl-shared-scripts.git//shared/security/eirctl.yaml
  - git::ssh://git@github.com/thepaulmacca-ensono/eirctl-shared-scripts.git//shared/docs/eirctl.yaml
  - git::ssh://git@github.com/thepaulmacca-ensono/eirctl-shared-scripts.git//shared/infra/terraform.yaml
  - git::ssh://git@github.com/thepaulmacca-ensono/eirctl-shared-scripts.git//shared/github/eirctl.yaml

pipelines:
  build:
    - task: terraform:build:clean
    - task: terraform:docs:asciidoc
      depends_on: terraform:build:clean
    - task: docs:docbook
      depends_on: terraform:docs:asciidoc
    - task: docs:markdown
      depends_on: docs:docbook
    - task: terraform:docs:asciidoc:readme
      depends_on: docs:markdown
    - task: terraform:build:copy
      depends_on: terraform:docs:asciidoc:readme
    - task: terraform:build:package
      depends_on: terraform:build:copy

  docs:
    - task: docs:generate

  scan:
    - task: scan:terraform:checkov

  lint:
    - task: lint:terraform:validate
    - task: lint:terraform:tflint
      depends_on: lint:terraform:validate

  tests:
    - task: terraform:init:false
    - task: terraform:tests
      depends_on: terraform:init:false

  # tag:retain:
  #   - task: git:tag
  #   - task: ado:pipeline:retain
  #     depends_on:
  #       - git:tag

  release:
    - task: github:release
