import:
  - ./build/eirctl/contexts.yaml
  - ./build/eirctl/tasks.yaml

pipelines:
  build:
    - task: build:clean
    # - task: terraform:docs
    #   depends_on: build:clean
    # - task: docs:docbook
    #   depends_on: terraform:docs
    # - task: docs:markdown
    #   depends_on: docs:docbook
    - task: build:copy
      # depends_on: docs:markdown
      # depends_on: terraform:docs
      depends_on: build:clean
    - task: build:package
      depends_on: build:copy

  docs:
    - task: docs:generate

  scan:
    - task: scan:terraform:checkov

  terraform:lint:
    - task: lint:terraform:format
    - task: lint:terraform:validate
      depends_on: lint:terraform:format
    - task: lint:terraform:tflint
      depends_on: lint:terraform:validate

  tests:
    - task: terraform:init
    - task: terraform:tests
      depends_on: terraform:init

  # tag:
  #   - task: git:tag
  #   - task: ado:pipeline:retain
  #     depends_on:
  #       - git:tag

  release:
    - task: github:release
